version: "3.5"
services:
  database:
    image: mysql:8
    restart: always
    expose: ["3306"]
    command:
      - mysqld
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --default-authentication-plugin=mysql_native_password
      - --innodb-buffer-pool-size=2G
      - --innodb-flush-method=O_DIRECT_NO_FSYNC
      - --innodb-log-file-size=128M
      - --innodb-log-files-in-group=2
    volumes:
      - type: volume
        source: zabbix-database
        target: /var/lib/mysql
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      TZ: Asia/Tokyo
      MYSQL_USER: zabbix
      MYSQL_DATABASE: zabbix-db
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD

  server:
    image: zabbix/zabbix-server-mysql:alpine-4.0-latest
    restart: always
    ports: ["10051:10051"]
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      DB_SERVER_HOST: database
      MYSQL_USER: zabbix
      MYSQL_DATABASE: zabbix-db
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    depends_on:
      - database

  web:
    image: zabbix/zabbix-web-nginx-mysql:alpine-4.0-latest
    restart: always
    ports: ["127.0.0.1:8051:80"]
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /etc/timezone:/etc/timezone:ro
    secrets:
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
    environment:
      PHP_TZ: Asia/Tokyo
      DB_SERVER_HOST: database
      ZBX_SERVER_HOST: server
      MYSQL_USER: zabbix
      MYSQL_DATABASE: zabbix-db
      MYSQL_PASSWORD_FILE: /run/secrets/MYSQL_PASSWORD
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/MYSQL_ROOT_PASSWORD
    depends_on:
      - server
      - database

secrets:
  MYSQL_PASSWORD:
    file: ./MYSQL_PASSWORD
  MYSQL_ROOT_PASSWORD:
    file: ./MYSQL_ROOT_PASSWORD

volumes:
  zabbix-database:
    name: zabbix-database
    driver: local

networks:
  default:
    name: zabbix
